# CIC Subpopulation Construction

To create a representative model of the agent interactions, we will use subpopulation modeling. We take all of the agents and cluster them based off of geographic location from full population actual transactional data from Jan - July 26 2020 xDai data.

Essentially, we are taking a graph zoom operation, bundling nodes together based off of their likeness. Nodes are constant with edges being transative. . All of the flows inside of the bundle become part of the self-loop flow. For example, within cluster 1, agent a can transaction with as b. This will not be reflected within our model as this is intra not inter cluster interactions.
 
## Graph Model of Current Spend Activity

We created a network graph of the CIC transaction data as a $G(N,E)$ weighted directed graph with source and target agents as nodes, $N$ and the edges as $E$. Tokens are used as the edge weight to denote the actual CIC flow between agents, as $i,j \in E$.

The observed data shows the actual payments between network actors that are transacting in CIC. The observed data does not show us shillings payments between actors, actors utility, or demand. We only know actual CIC spends between agents.     


## Saving Clustering Results
At the bottom of this notebook, we calculate the median, 1st quartile, 3rd quartile, mean, standard deviation, utility types ordering, and utility types probability. These values can then be copied into the ```subpopulation_clusters.py``` in the simulation folders for use in the simulations.

In [3]:
# import libraries
import networkx as nx
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
%matplotlib inline

## Data Dump as of 8-31-2020
Jan - July 26 2020 xDai Blockchain data
https://www.grassrootseconomics.org/research

In [4]:
# import the data
transactions = pd.read_csv('data/tx_all_pub_all_time.csv')
users = pd.read_csv('data/users_all_pub_all_time.csv')

/home/aclarkdata/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3071: DtypeWarning: Columns (3,6) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [7]:
transactions.head()

,id,timeset,transfer_subtype,transfer_use,source,s_comm_tkn,s_gender,s_location_path,s_location_lat,s_location_lon,...,t_gender,t_location_path,t_location_lat,t_location_lon,t_business_type,tx_token,weight,type,token_name,token_address
0,1,2020-01-25 19:13:17.731529,DISBURSEMENT,NaN,0xEDA5C9B75Fdb3B9bdAB987A704632280Cf93084F,None,NaN,None,None,None,...,female,None,None,None,Savings Group,NaN,18000.000000,directed,Sarafu,0x0Fd6e8F2320C90e9D4b3A5bd888c4D556d20AbD4
1,2,2020-01-25 19:13:19.056070,DISBURSEMENT,NaN,0xEDA5C9B75Fdb3B9bdAB987A704632280Cf93084F,None,NaN,None,None,None,...,male,"Kilifi,Kilifi,Coastal Kenya",39.85,-3.6333,Farming/Labour,NaN,9047.660892,directed,Sarafu,0x0Fd6e8F2320C90e9D4b3A5bd888c4D556d20AbD4
2,3,2020-01-25 19:13:20.288346,DISBURSEMENT,NaN,0xEDA5C9B75Fdb3B9bdAB987A704632280Cf93084F,None,NaN,None,None,None,...,male,"Kilifi,Kilifi,Coastal Kenya",39.85,-3.6333,Farming/Labour,NaN,25378.726002,directed,Sarafu,0x0Fd6e8F2320C90e9D4b3A5bd888c4D556d20AbD4
3,4,2020-01-25 19:13:21.478850,DISBURSEMENT,NaN,0xEDA5C9B75Fdb3B9bdAB987A704632280Cf93084F,None,NaN,None,None,None,...,male,"Kilifi,Kilifi,Coastal Kenya",39.85,-3.6333,Health,NaN,4495.932576,directed,Sarafu,0x0Fd6e8F2320C90e9D4b3A5bd888c4D556d20AbD4
4,19,2020-01-26 15:32:36.540298,DISBURSEMENT,NaN,0xEDA5C9B75Fdb3B9bdAB987A704632280Cf93084F,None,NaN,None,None,None,...,male,"Kawangware,Nairobi,Nairobi,Nairobi",36.751643,-1.2784631,Food/Water,NaN,621.689801,directed,Sarafu,0x0Fd6e8F2320C90e9D4b3A5bd888c4D556d20AbD4

In [6]:
transactions.columns

Index(['id', 'timeset', 'transfer_subtype', 'transfer_use', 'source',
       's_comm_tkn', 's_gender', 's_location_path', 's_location_lat',
       's_location_lon', 's_business_type', 'target', 't_comm_tkn', 't_gender',
       't_location_path', 't_location_lat', 't_location_lon',
       't_business_type', 'tx_token', 'weight', 'type', 'token_name',
       'token_address'],
      dtype='object')

In [4]:
transactions.transfer_subtype.value_counts(normalize=True).to_dict()

{'STANDARD': 0.5085207861177824,
 'DISBURSEMENT': 0.35574873997902784,
 'RECLAMATION': 0.13483070053783444,
 'AGENT_OUT': 0.0008997733653553429}

Based on the data dictionary provided by Grassroots Economics, we know that the transfer subtype codes are:

* DISBURSEMENT = from Grassroots Economics
* RECLAMATION = Back to GE, 
* STANDARD = a trade between users, 
* AGENT = when a group account is cashing out


For purposes of our analysis, we will subset to STANDARD transactions.

In [8]:
transactions_subset = transactions[transactions['transfer_subtype'] == 'STANDARD']
transactions_subset = transactions_subset[transactions_subset['token_name']=='Sarafu']

In [9]:
users.head()

,id,start,label,gender,location,lat,lon,held_roles,business_type,bal,...,otxns_in,otxns_out,ounique_in,ounique_out,svol_in,svol_out,stxns_in,stxns_out,sunique_in,sunique_out
0,13817,2020-04-13 13:38:04.665198,13817,male,"Bofu,Kwale,Coastal Kenya",39.4333,-3.9666,BENEFICIARY,Farming/Labour,24.46,...,9,1,2,1,0.0,734.0,0,6,0,3
1,9149,2020-02-04 11:37:26.144440,9149,female,None,None,None,BENEFICIARY,Fuel/Energy,24.04,...,13,0,2,0,27461.0,28602.0,13,22,4,3
2,12449,2020-04-01 00:29:41.190138,12449,female,None,None,None,BENEFICIARY,System,138.00,...,2,2,2,1,0.0,22.0,0,3,0,2
3,9736,2020-02-11 13:55:03.570515,9736,male,"Bofu,Kwale,Coastal Kenya",39.4333,-3.9666,BENEFICIARY,Farming/Labour,920.00,...,2,2,2,1,2500.0,2040.0,6,2,5,1
4,13814,2020-04-13 13:24:14.510171,13814,male,"Bofu,Kwale,Coastal Kenya",39.4333,-3.9666,BENEFICIARY,Farming/Labour,36.96,...,4,1,2,1,2.0,516.0,1,4,0,3

In [10]:
users['business_type'].value_counts(normalize=True).to_dict()

{'Farming/Labour': 0.39523369421705834,
 'Food/Water': 0.24069184050699763,
 'Shop': 0.1386651703195141,
 'None': 0.10176260892527066,
 'Fuel/Energy': 0.06198838130446264,
 'Transport': 0.03653947715870082,
 'Education': 0.01132162661737523,
 'Savings Group': 0.00538024821758648,
 'Health': 0.004489041457618167,
 'Environment': 0.0027726432532347504,
 'System': 0.0008251914444151043,
 'Chama': 9.902297332981252e-05,
 'Volunteer': 9.902297332981252e-05,
 'Staff': 6.601531555320834e-05,
 'M-pesa': 3.300765777660417e-05,
 'Game': 3.300765777660417e-05}

## Combine user and transaction tables 
# TODO: Need to update joins

Combine user and transaction tables on both the source and target features.

In [11]:
user_subset = users[['bal','xDAI_blockchain_address']]

In [12]:
transactions_subset

,id,timeset,transfer_subtype,transfer_use,source,s_comm_tkn,s_gender,s_location_path,s_location_lat,s_location_lon,...,t_gender,t_location_path,t_location_lat,t_location_lon,t_business_type,tx_token,weight,type,token_name,token_address
40233,170140,2020-04-30 10:43:45.170528,STANDARD,Donation,0xC1697C1326fD192438515fE2F7E4cCb0C705C5d2,None,male,"Kilifi,Kilifi,Coastal Kenya",39.85,-3.6333,...,male,"Kilifi,Kilifi,Coastal Kenya",39.85,-3.6333,Farming/Labour,NaN,9007.0,directed,Sarafu,0x0Fd6e8F2320C90e9D4b3A5bd888c4D556d20AbD4
40235,10,2020-01-26 08:26:22.521902,STANDARD,Education,0xBAB77A20a757e8438DfaBF01D5F36DD12d862B31,None,male,"Kilifi,Kilifi,Coastal Kenya",39.85,-3.6333,...,male,None,None,None,Farming/Labour,NaN,100.0,directed,Sarafu,0x0Fd6e8F2320C90e9D4b3A5bd888c4D556d20AbD4
40236,11,2020-01-26 08:27:26.757372,STANDARD,Education,0xD95954e3fCd2f09A6Be5931D24f731eFa63BF435,None,male,"Kilifi,Kilifi,Coastal Kenya",39.85,-3.6333,...,male,"Kilifi,Kilifi,Coastal Kenya",39.85,-3.6333,Farming/Labour,NaN,2.0,directed,Sarafu,0x0Fd6e8F2320C90e9D4b3A5bd888c4D556d20AbD4
40237,13,2020-01-26 08:32:05.154096,STANDARD,Savings Group,0xBAB77A20a757e8438DfaBF01D5F36DD12d862B31,None,male,"Kilifi,Kilifi,Coastal Kenya",39.85,-3.6333,...,male,None,None,None,Farming/Labour,NaN,23.0,directed,Sarafu,0x0Fd6e8F2320C90e9D4b3A5bd888c4D556d20AbD4
40238,15,2020-01-26 08:38:42.186525,STANDARD,Fuel/Energy,0x4AfD04b9eD17759B362c8C929207Fe7ad81C39d3,None,male,None,None,None,...,male,"Kilifi,Kilifi,Coastal Kenya",39.85,-3.6333,Farming/Labour,NaN,12.0,directed,Sarafu,0x0Fd6e8F2320C90e9D4b3A5bd888c4D556d20AbD4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
318857,412546,2020-07-25 11:13:12.252972,STANDARD,NaN,0xe1668dBBa828AaCeF2fe3D4BB639BA7fc918a4D9,None,male,"Mnyenzeni,Kwale,Coastal Kenya",39.5,-3.9833,...,male,"Mnyenzeni,Kwale,Coastal Kenya",39.5,-3.9833,Farming/Labour,NaN,400.0,directed,Sarafu,0x0Fd6e8F2320C90e9D4b3A5bd888c4D556d20AbD4
318858,412538,2020-07-25 11:11:13.231150,STANDARD,NaN,0xe0Fd166528A39D03a3CDDE75B6C76dAD60e90F9B,None,male,"Mnyenzeni,Kwale,Coastal Kenya",39.5,-3.9833,...,male,"Mnyenzeni,Kwale,Coastal Kenya",39.5,-3.9833,Farming/Labour,NaN,250.0,directed,Sarafu,0x0Fd6e8F2320C90e9D4b3A5bd888c4D556d20AbD4
318859,412229,2020-07-25 09:17:20.305846,STANDARD,NaN,0x56569DA45893aF1bAcd188B6d10873a18c92c618,None,Unknown gender,None,None,None,...,male,"Mukuru Kayaba Village,Plainsview Road,South B,...",36.84450844411661,-1.3112602,Fuel/Energy,NaN,20.0,directed,Sarafu,0x0Fd6e8F2320C90e9D4b3A5bd888c4D556d20AbD4
318860,412197,2020-07-25 09:04:43.477626,STANDARD,NaN,0xDC25113f73EB46d1a5Bb7C8F460d549e77B54f77,None,male,"Mukuru Kayaba Village,Plainsview Road,South B,...",36.84450844411661,-1.3112602,...,male,"Mukuru Kayaba Village,Plainsview Road,South B,...",36.84450844411661,-1.3112602,Fuel/Energy,NaN,20.0,directed,Sarafu,0x0Fd6e8F2320C90e9D4b3A5bd888c4D556d20AbD4
318861,412216,2020-07-25 09:11:23.250023,STANDARD,NaN,0xDC25113f73EB46d1a5Bb7C8F460d549e77B54f77,None,male,"Mukuru Kayaba Village,Plainsview Road,South B,...",36.84450844411661,-1.3112602,...,male,"Mukuru Kayaba Village,Plainsview Road,South B,...",36.84450844411661,-1.3112602,Fuel/Energy,NaN,380.0,directed,Sarafu,0x0Fd6e8F2320C90e9D4b3A5bd888c4D556d20AbD4

In [13]:
transactions_subset_v1 = transactions_subset.merge(user_subset, how='left', left_on='source', right_on='xDAI_blockchain_address')
transactions_subset_v1['s_bal'] = transactions_subset_v1['bal']
del transactions_subset_v1['bal']
transactions_subset_v1['s_xDAI_blockchain_address'] = transactions_subset_v1['xDAI_blockchain_address']
del transactions_subset_v1['xDAI_blockchain_address']

In [14]:
transactions_subset_v2 = transactions_subset_v1.merge(user_subset, how='left', left_on='target', right_on='xDAI_blockchain_address')

In [15]:
transactions_subset_v2 = transactions_subset_v1.merge(user_subset, how='left', left_on='target', right_on='xDAI_blockchain_address')
transactions_subset_v2['t_bal'] = transactions_subset_v2['bal']
del transactions_subset_v2['bal']
transactions_subset_v2['t_xDAI_blockchain_address'] = transactions_subset_v2['xDAI_blockchain_address']
del transactions_subset_v2['xDAI_blockchain_address']

In [18]:
combined = transactions_subset_v2.copy()

In [20]:
combined.head()

,id,timeset,transfer_subtype,transfer_use,source,s_comm_tkn,s_gender,s_location_path,s_location_lat,s_location_lon,...,t_business_type,tx_token,weight,type,token_name,token_address,s_bal,s_xDAI_blockchain_address,t_bal,t_xDAI_blockchain_address
0,170140,2020-04-30 10:43:45.170528,STANDARD,Donation,0xC1697C1326fD192438515fE2F7E4cCb0C705C5d2,None,male,"Kilifi,Kilifi,Coastal Kenya",39.85,-3.6333,...,Farming/Labour,NaN,9007.0,directed,Sarafu,0x0Fd6e8F2320C90e9D4b3A5bd888c4D556d20AbD4,56.660892,0xC1697C1326fD192438515fE2F7E4cCb0C705C5d2,5674.886002,0xBAB77A20a757e8438DfaBF01D5F36DD12d862B31
1,10,2020-01-26 08:26:22.521902,STANDARD,Education,0xBAB77A20a757e8438DfaBF01D5F36DD12d862B31,None,male,"Kilifi,Kilifi,Coastal Kenya",39.85,-3.6333,...,Farming/Labour,NaN,100.0,directed,Sarafu,0x0Fd6e8F2320C90e9D4b3A5bd888c4D556d20AbD4,5674.886002,0xBAB77A20a757e8438DfaBF01D5F36DD12d862B31,902.500000,0x4AB73CfaC1732a9DcD74BdB4C9605f21832D7C72
2,11,2020-01-26 08:27:26.757372,STANDARD,Education,0xD95954e3fCd2f09A6Be5931D24f731eFa63BF435,None,male,"Kilifi,Kilifi,Coastal Kenya",39.85,-3.6333,...,Farming/Labour,NaN,2.0,directed,Sarafu,0x0Fd6e8F2320C90e9D4b3A5bd888c4D556d20AbD4,2958.582576,0xD95954e3fCd2f09A6Be5931D24f731eFa63BF435,5674.886002,0xBAB77A20a757e8438DfaBF01D5F36DD12d862B31
3,13,2020-01-26 08:32:05.154096,STANDARD,Savings Group,0xBAB77A20a757e8438DfaBF01D5F36DD12d862B31,None,male,"Kilifi,Kilifi,Coastal Kenya",39.85,-3.6333,...,Farming/Labour,NaN,23.0,directed,Sarafu,0x0Fd6e8F2320C90e9D4b3A5bd888c4D556d20AbD4,5674.886002,0xBAB77A20a757e8438DfaBF01D5F36DD12d862B31,902.500000,0x4AB73CfaC1732a9DcD74BdB4C9605f21832D7C72
4,15,2020-01-26 08:38:42.186525,STANDARD,Fuel/Energy,0x4AfD04b9eD17759B362c8C929207Fe7ad81C39d3,None,male,None,None,None,...,Farming/Labour,NaN,12.0,directed,Sarafu,0x0Fd6e8F2320C90e9D4b3A5bd888c4D556d20AbD4,609.000000,0x4AfD04b9eD17759B362c8C929207Fe7ad81C39d3,5674.886002,0xBAB77A20a757e8438DfaBF01D5F36DD12d862B31

# TODO:

By using the s_location_lat, s_location_long and t_location_lat, t_location_lat:
1. Plot individuals to on a map to show their locations. Example methods: - https://jakevdp.github.io/PythonDataScienceHandbook/04.13-geographic-data-with-basemap.html https://towardsdatascience.com/geopandas-101-plot-any-data-with-a-latitude-and-longitude-on-a-map-98e01944b972 https://geopandas.org/index.html https://stackoverflow.com/questions/53233228/plot-latitude-longitude-from-csv-in-python-3-6 https://examples.pyviz.org/gerrymandering/gerrymandering.html
2. Describe what you see in the groups
3. Use Kmeans clustering, another clustering methodology or simple heurstic to group data into subpopulations
4. Update data in the initialization section below

## Descriptive statistics - TODO
Update from clusters

Calculate relevant statistics, such as median, mean, etc for creating probability distributions in the subpopulation model.

In [18]:
# compute median, Q1,Q3, mean, and sigma
clustersMedianSourceBalance = []
clusters1stQSourceBalance = []
clusters3rdQSourceBalance = []
clustersMu = []
clustersSigma = []
for i in range(0,len(combined.cluster.unique())):
    temp = combined[combined['cluster']==i]
    clustersMu.append(round(temp.weight.mean(),2))
    clustersSigma.append(round(temp.weight.std(),2))
    clustersMedianSourceBalance.append(round(temp.weight.median(),2))
    clusters1stQSourceBalance.append(round(temp.s_bal.quantile(0.25),2))
    clusters3rdQSourceBalance.append(round(temp.s_bal.quantile(0.75),2))

In [23]:
clusters = []
for i in range(0,len(combined.cluster.unique())):
    clusters.append(str(i))
    
    
mixingAgents = clusters.copy()
mixingAgents.append('external')

In [26]:
UtilityTypesOrdered = {}
for i in range(0,len(combined.cluster.unique())):
    UtilityTypesOrdered[str(i)] = dict(zip(list(combined[combined['cluster']==i].t_business_type.value_counts(normalize=True).to_dict().keys()),list(combined[combined['cluster']==i].t_business_type.value_counts(normalize=True).to_dict().values())))
    
UtilityTypesOrdered['external'] =  {'Food/Water':1,
                                            'Fuel/Energy':2,
                                            'Health':3,
                                            'Education':4,
                                            'Savings Group':5,
                                            'Shop':6}

In [28]:
utilityTypesProbability = {}
for i in range(0,len(combined.cluster.unique())):
    utilityTypesProbability[str(i)] = combined[combined['cluster']==i].t_business_type.value_counts(normalize=True).to_dict()
    
    
utilityTypesProbability['external'] = {'Food/Water':0.6,
                                            'Fuel/Energy':0.10,
                                            'Health':0.03,
                                            'Education':0.015,
                                            'Savings Group':0.065,
                                            'Shop':0.19}

In [ ]:
# Create initilization file (copy from here) 

clusters = ['0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 '10',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '19',
 '20',
 '21',
 '22',
 '23',
 '24',
 '25',
 '26',
 '27',
 '28',
 '29',
 '30',
 '31',
 '32',
 '33',
 '34',
 '35',
 '36',
 '37',
 '38',
 '39',
 '40',
 '41',
 '42',
 '43',
 '44',
 '45',
 '46',
 '47',
 '48',
 '49']

mixingAgents = ['0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 '10',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '19',
 '20',
 '21',
 '22',
 '23',
 '24',
 '25',
 '26',
 '27',
 '28',
 '29',
 '30',
 '31',
 '32',
 '33',
 '34',
 '35',
 '36',
 '37',
 '38',
 '39',
 '40',
 '41',
 '42',
 '43',
 '44',
 '45',
 '46',
 '47',
 '48',
 '49',
 'external']


clustersMedianSourceBalance = [150.0,
 340.0,
 250.0,
 20.0,
 330.0,
 320.0,
 240.0,
 300.0,
 300.0,
 50.0,
 900.0,
 120.0,
 400.0,
 180.0,
 300.0,
 6000.0,
 132.5,
 130.0,
 160.0,
 5000.0,
 150.0,
 10000.0,
 200.0,
 10000.0,
 200.0,
 200.0,
 35000.0,
 20000.0,
 100.0,
 500.0,
 425.0,
 13320.0,
 500.0,
 500.0,
 1000.0,
 390.0,
 150.0,
 250.0,
 45000.0,
 36300.0,
 960.0,
 120.0,
 200.0,
 100.0,
 220.0,
 600.0,
 62000.0,
 500.0,
 900.0,
 486.0]

clusters1stQSourceBalance = [56.0,
 118.46,
 105.0,
 64767.51,
 251652.0,
 124.5,
 4139.28,
 146.1,
 1002.5,
 17145.78,
 52676.2,
 100.0,
 121082.43,
 112.0,
 28849.43,
 27619.22,
 66.36,
 251652.0,
 148.0,
 38653.54,
 67.22,
 121082.43,
 6429.46,
 555.04,
 104.48,
 96.43,
 52676.2,
 251652.0,
 64.73,
 36824.5,
 15182.03,
 485.94,
 21660.89,
 11210.0,
 100579.18,
 100.46,
 2845.01,
 3338.98,
 1274.91,
 6724.88,
 38653.54,
 114.5,
 68.0,
 100.0,
 20.93,
 14050.3,
 63145.96,
 9276.23,
 63234.8,
 64767.51]

clusters3rdQSourceBalance = [403.96,
 506.6,
 592.96,
 64767.51,
 251652.0,
 1501.41,
 7214.9,
 869.82,
 1557.01,
 18304.36,
 55142.93,
 419.96,
 121082.43,
 816.3,
 38653.54,
 37106.89,
 770.65,
 251652.0,
 838.46,
 38653.54,
 315.0,
 121082.43,
 9074.79,
 5726.66,
 602.02,
 437.96,
 63234.8,
 251652.0,
 425.0,
 40953.15,
 17145.78,
 6349.27,
 25695.83,
 13156.46,
 100579.18,
 819.33,
 4158.5,
 5597.38,
 2823.81,
 20030.91,
 51710.52,
 537.94,
 542.92,
 415.43,
 895.66,
 18304.36,
 63145.96,
 14050.3,
 64767.51,
 64767.51]

clustersMu = [329.98,
 588.11,
 469.93,
 492.32,
 2443.89,
 565.21,
 1120.5,
 408.1,
 550.09,
 503.42,
 2478.89,
 349.93,
 9354.55,
 453.69,
 4298.1,
 7508.1,
 376.86,
 8074.0,
 333.75,
 7691.43,
 362.68,
 15562.5,
 672.28,
 10809.6,
 274.98,
 405.46,
 34555.56,
 14338.57,
 255.48,
 1229.44,
 1470.23,
 14590.61,
 1527.75,
 770.73,
 1039.05,
 503.7,
 362.11,
 499.51,
 45000.0,
 37504.55,
 1941.82,
 262.96,
 702.23,
 168.57,
 2000.58,
 1383.32,
 65333.33,
 1454.43,
 1483.11,
 1853.03]

clustersSigma = [583.23,
 1501.26,
 966.32,
 1452.2,
 6789.39,
 847.29,
 2228.12,
 483.5,
 852.2,
 1170.38,
 3256.26,
 1174.55,
 16235.99,
 841.35,
 7696.91,
 6814.68,
 785.21,
 10886.9,
 712.65,
 8713.11,
 708.54,
 18542.24,
 1164.0,
 3682.08,
 340.99,
 624.76,
 8171.77,
 15060.34,
 461.52,
 1774.39,
 4617.97,
 4770.82,
 2641.75,
 1133.41,
 767.87,
 437.68,
 652.72,
 761.07,
 7071.07,
 5274.96,
 2716.8,
 572.43,
 1553.21,
 210.61,
 4477.94,
 1798.73,
 31134.12,
 2147.9,
 1900.27,
 2909.68]


# nested dictionary
UtilityTypesOrdered = {'0': {'Food/Water': 0.4119323241317899,
  'Farming/Labour': 0.26090828138913624,
  'Shop': 0.17916295636687443,
  'Savings Group': 0.07266251113089937,
  'Fuel/Energy': 0.034194122885129116,
  'Transport': 0.02617987533392698,
  'Health': 0.006767586821015138,
  'Education': 0.004096170970614425,
  'None': 0.004096170970614425},
 '1': {'Food/Water': 1.0},
 '2': {'Savings Group': 0.87890625,
  'Health': 0.08984375,
  'Food/Water': 0.03125},
 '3': {'Savings Group': 0.4905964535196131,
  'Farming/Labour': 0.3610961848468565,
  'Food/Water': 0.14830736163353037},
 '4': {'Farming/Labour': 0.2843866171003718,
  'Shop': 0.25650557620817843,
  'Fuel/Energy': 0.17843866171003717,
  'Food/Water': 0.16171003717472118,
  'None': 0.10966542750929369,
  'Savings Group': 0.0055762081784386614,
  'Transport': 0.0037174721189591076},
 '5': {'Farming/Labour': 0.421875,
  'Food/Water': 0.421875,
  'Shop': 0.0625,
  'Savings Group': 0.03125,
  'Fuel/Energy': 0.03125,
  'Transport': 0.03125},
 '6': {'Savings Group': 0.6008097165991902,
  'Food/Water': 0.35870445344129553,
  'Shop': 0.04048582995951417},
 '7': {'Farming/Labour': 0.4346590909090909,
  'Food/Water': 0.2869318181818182,
  'Shop': 0.1278409090909091,
  'Fuel/Energy': 0.07670454545454546,
  'Savings Group': 0.03977272727272727,
  'Education': 0.017045454545454544,
  'None': 0.011363636363636364,
  'Transport': 0.002840909090909091,
  'Health': 0.002840909090909091},
 '8': {'Savings Group': 1.0},
 '9': {'Savings Group': 0.7142857142857143,
  'Food/Water': 0.18181818181818182,
  'Farming/Labour': 0.07792207792207792,
  'Education': 0.025974025974025976},
 '10': {'Food/Water': 0.3499875508340941,
  'Farming/Labour': 0.3162088140094614,
  'Shop': 0.21047389824881732,
  'Transport': 0.03950535314133953,
  'None': 0.03386173126400531,
  'Fuel/Energy': 0.022491493069964313,
  'Education': 0.01709685451074778,
  'Savings Group': 0.006473566271059839,
  'Environment': 0.002157855423686613,
  'Health': 0.0016598887874512407,
  'Chama': 8.299443937256204e-05},
 '11': {'Savings Group': 0.4873417721518987,
  'Food/Water': 0.3377445339470656,
  'Education': 0.09723820483314154,
  'Farming/Labour': 0.06271576524741082,
  'Shop': 0.014959723820483314},
 '12': {'Food/Water': 0.34994337485843713,
  'Shop': 0.2332955832389581,
  'Farming/Labour': 0.19592298980747452,
  'Fuel/Energy': 0.057757644394110984,
  'Savings Group': 0.053227633069082674,
  'Education': 0.05096262740656852,
  'None': 0.026047565118912798,
  'Transport': 0.020385050962627407,
  'Health': 0.011325028312570781,
  'Environment': 0.0011325028312570782},
 '13': {'Savings Group': 0.3712871287128713,
  'Food/Water': 0.247974797479748,
  'Shop': 0.19801980198019803,
  'Fuel/Energy': 0.08235823582358236,
  'Health': 0.07605760576057606,
  'Farming/Labour': 0.024302430243024302},
 '14': {'Savings Group': 1.0},
 '15': {'Savings Group': 1.0},
 '16': {'Savings Group': 0.5, 'Food/Water': 0.5},
 '17': {'Savings Group': 0.7335701598579041,
  'Shop': 0.17584369449378331,
  'Food/Water': 0.0905861456483126},
 '18': {'Savings Group': 0.6984126984126984,
  'Food/Water': 0.23809523809523808,
  'Farming/Labour': 0.06349206349206349},
 '19': {'Savings Group': 1.0},
 '20': {'Savings Group': 1.0},
 '21': {'Farming/Labour': 0.47619047619047616,
  'Food/Water': 0.3333333333333333,
  'Shop': 0.09523809523809523,
  'Fuel/Energy': 0.047619047619047616,
  'Transport': 0.047619047619047616},
 '22': {'Food/Water': 0.33040588654165676,
  'Farming/Labour': 0.3209114645145977,
  'Shop': 0.164016140517446,
  'None': 0.06147638262520769,
  'Fuel/Energy': 0.05008307619273677,
  'Transport': 0.028957987182530263,
  'Savings Group': 0.023973415618324233,
  'Education': 0.014478993591265131,
  'Health': 0.0035604082601471635,
  'Environment': 0.0011868027533823878,
  'Staff': 0.00047472110135295516,
  'Chama': 0.00023736055067647758,
  'Game': 0.00023736055067647758},
 '23': {'Savings Group': 0.8323424494649228,
  'Farming/Labour': 0.16765755053507728},
 '24': {'Farming/Labour': 0.38481675392670156,
  'Food/Water': 0.3717277486910995,
  'Shop': 0.1387434554973822,
  'Fuel/Energy': 0.05235602094240838,
  'Transport': 0.02356020942408377,
  'Savings Group': 0.01832460732984293,
  'Education': 0.007853403141361256,
  'Staff': 0.002617801047120419},
 '25': {'Savings Group': 0.7916666666666666,
  'Food/Water': 0.20833333333333334},
 '26': {'Savings Group': 0.7442348008385744, 'Food/Water': 0.2557651991614256},
 '27': {'Food/Water': 0.3333333333333333,
  'Farming/Labour': 0.25,
  'Health': 0.25,
  'Savings Group': 0.08333333333333333,
  'Fuel/Energy': 0.08333333333333333},
 '28': {'Food/Water': 1.0},
 '29': {'Food/Water': 0.27335640138408307,
  'Farming/Labour': 0.23529411764705882,
  'Shop': 0.21972318339100347,
  'Fuel/Energy': 0.21280276816608998,
  'None': 0.03806228373702422,
  'Education': 0.006920415224913495,
  'Transport': 0.006920415224913495,
  'Savings Group': 0.005190311418685121,
  'Staff': 0.0017301038062283738},
 '30': {'Food/Water': 0.36228287841191065,
  'Shop': 0.2679900744416873,
  'Farming/Labour': 0.21712158808933002,
  'Savings Group': 0.08436724565756824,
  'Education': 0.02481389578163772,
  'Fuel/Energy': 0.018610421836228287,
  'Transport': 0.017369727047146403,
  'None': 0.0037220843672456576,
  'Health': 0.0024813895781637717,
  'Environment': 0.0012406947890818859},
 '31': {'Savings Group': 0.8,
  'Food/Water': 0.13333333333333333,
  'Shop': 0.06666666666666667},
 '32': {'Savings Group': 0.7444444444444445,
  'Farming/Labour': 0.2,
  'Food/Water': 0.05555555555555555},
 '33': {'Food/Water': 0.33343474292668085,
  'Farming/Labour': 0.28414968055978096,
  'Savings Group': 0.18892607240644965,
  'Shop': 0.1146942500760572,
  'Fuel/Energy': 0.06936416184971098,
  'None': 0.006693033160937024,
  'Education': 0.0027380590203833284},
 '34': {'Savings Group': 1.0},
 '35': {'Food/Water': 0.3829787234042553,
  'Farming/Labour': 0.2390488110137672,
  'Shop': 0.1902377972465582,
  'Savings Group': 0.07259073842302878,
  'Transport': 0.060075093867334166,
  'Health': 0.030037546933667083,
  'Fuel/Energy': 0.016270337922403004,
  'None': 0.0050062578222778474,
  'Education': 0.0037546933667083854},
 '36': {'Savings Group': 1.0},
 '37': {'Farming/Labour': 0.5454545454545454,
  'Food/Water': 0.36363636363636365,
  'Savings Group': 0.045454545454545456,
  'Shop': 0.045454545454545456},
 '38': {'Savings Group': 1.0},
 '39': {'Savings Group': 1.0},
 '40': {'Farming/Labour': 0.3595236417447678,
  'Food/Water': 0.3165386512578395,
  'Shop': 0.18842928616728913,
  'Fuel/Energy': 0.05108871820167712,
  'None': 0.0360439715312522,
  'Transport': 0.022443802409978154,
  'Education': 0.01039391163413431,
  'Savings Group': 0.00842083010358678,
  'Health': 0.004545134240011275,
  'Staff': 0.0011627087590726517,
  'Environment': 0.0010570079627933197,
  'System': 0.00035233598759777326},
 '41': {'Food/Water': 0.33003300330033003,
  'Farming/Labour': 0.2739273927392739,
  'Shop': 0.1782178217821782,
  'Savings Group': 0.13861386138613863,
  'Health': 0.0429042904290429,
  'Fuel/Energy': 0.0165016501650165,
  'Transport': 0.0165016501650165,
  'Education': 0.0033003300330033004},
 '42': {'Savings Group': 0.8661740558292282, 'Health': 0.13382594417077176},
 '43': {'Savings Group': 1.0},
 '44': {'Food/Water': 0.4805194805194805,
  'Shop': 0.14285714285714285,
  'Savings Group': 0.14285714285714285,
  'Farming/Labour': 0.13636363636363635,
  'Health': 0.06493506493506493,
  'Transport': 0.012987012987012988,
  'Environment': 0.012987012987012988,
  'Fuel/Energy': 0.006493506493506494},
 '45': {'Food/Water': 0.35471100554235946,
  'Farming/Labour': 0.2414885193982581,
  'Shop': 0.23198733174980204,
  'Education': 0.03800475059382423,
  'None': 0.035629453681710214,
  'Transport': 0.035629453681710214,
  'Fuel/Energy': 0.028503562945368172,
  'Savings Group': 0.02454473475851148,
  'Health': 0.006334125098970704,
  'Environment': 0.001583531274742676,
  'Staff': 0.000791765637371338,
  'System': 0.000791765637371338},
 '46': {'Savings Group': 0.6981132075471698,
  'Health': 0.18867924528301888,
  'Food/Water': 0.09433962264150944,
  'Shop': 0.018867924528301886},
 '47': {'Savings Group': 0.5555555555555556,
  'Farming/Labour': 0.2222222222222222,
  'Food/Water': 0.2222222222222222},
 '48': {'Food/Water': 0.38795180722891565,
  'Savings Group': 0.38313253012048193,
  'Health': 0.10120481927710843,
  'Shop': 0.09879518072289156,
  'Fuel/Energy': 0.016867469879518072,
  'Farming/Labour': 0.012048192771084338},
 '49': {'Food/Water': 0.3829787234042553,
  'Savings Group': 0.3829787234042553,
  'Education': 0.19148936170212766,
  'Fuel/Energy': 0.0425531914893617},
 'external': {'Food/Water': 1,
  'Fuel/Energy': 2,
  'Health': 3,
  'Education': 4,
  'Savings Group': 5,
  'Shop': 6}}
    
#  nested dictionary 
utilityTypesProbability = {'0': {'Food/Water': 0.4119323241317899,
  'Farming/Labour': 0.26090828138913624,
  'Shop': 0.17916295636687443,
  'Savings Group': 0.07266251113089937,
  'Fuel/Energy': 0.034194122885129116,
  'Transport': 0.02617987533392698,
  'Health': 0.006767586821015138,
  'Education': 0.004096170970614425,
  'None': 0.004096170970614425},
 '1': {'Food/Water': 1.0},
 '2': {'Savings Group': 0.87890625,
  'Health': 0.08984375,
  'Food/Water': 0.03125},
 '3': {'Savings Group': 0.4905964535196131,
  'Farming/Labour': 0.3610961848468565,
  'Food/Water': 0.14830736163353037},
 '4': {'Farming/Labour': 0.2843866171003718,
  'Shop': 0.25650557620817843,
  'Fuel/Energy': 0.17843866171003717,
  'Food/Water': 0.16171003717472118,
  'None': 0.10966542750929369,
  'Savings Group': 0.0055762081784386614,
  'Transport': 0.0037174721189591076},
 '5': {'Farming/Labour': 0.421875,
  'Food/Water': 0.421875,
  'Shop': 0.0625,
  'Savings Group': 0.03125,
  'Fuel/Energy': 0.03125,
  'Transport': 0.03125},
 '6': {'Savings Group': 0.6008097165991902,
  'Food/Water': 0.35870445344129553,
  'Shop': 0.04048582995951417},
 '7': {'Farming/Labour': 0.4346590909090909,
  'Food/Water': 0.2869318181818182,
  'Shop': 0.1278409090909091,
  'Fuel/Energy': 0.07670454545454546,
  'Savings Group': 0.03977272727272727,
  'Education': 0.017045454545454544,
  'None': 0.011363636363636364,
  'Transport': 0.002840909090909091,
  'Health': 0.002840909090909091},
 '8': {'Savings Group': 1.0},
 '9': {'Savings Group': 0.7142857142857143,
  'Food/Water': 0.18181818181818182,
  'Farming/Labour': 0.07792207792207792,
  'Education': 0.025974025974025976},
 '10': {'Food/Water': 0.3499875508340941,
  'Farming/Labour': 0.3162088140094614,
  'Shop': 0.21047389824881732,
  'Transport': 0.03950535314133953,
  'None': 0.03386173126400531,
  'Fuel/Energy': 0.022491493069964313,
  'Education': 0.01709685451074778,
  'Savings Group': 0.006473566271059839,
  'Environment': 0.002157855423686613,
  'Health': 0.0016598887874512407,
  'Chama': 8.299443937256204e-05},
 '11': {'Savings Group': 0.4873417721518987,
  'Food/Water': 0.3377445339470656,
  'Education': 0.09723820483314154,
  'Farming/Labour': 0.06271576524741082,
  'Shop': 0.014959723820483314},
 '12': {'Food/Water': 0.34994337485843713,
  'Shop': 0.2332955832389581,
  'Farming/Labour': 0.19592298980747452,
  'Fuel/Energy': 0.057757644394110984,
  'Savings Group': 0.053227633069082674,
  'Education': 0.05096262740656852,
  'None': 0.026047565118912798,
  'Transport': 0.020385050962627407,
  'Health': 0.011325028312570781,
  'Environment': 0.0011325028312570782},
 '13': {'Savings Group': 0.3712871287128713,
  'Food/Water': 0.247974797479748,
  'Shop': 0.19801980198019803,
  'Fuel/Energy': 0.08235823582358236,
  'Health': 0.07605760576057606,
  'Farming/Labour': 0.024302430243024302},
 '14': {'Savings Group': 1.0},
 '15': {'Savings Group': 1.0},
 '16': {'Savings Group': 0.5, 'Food/Water': 0.5},
 '17': {'Savings Group': 0.7335701598579041,
  'Shop': 0.17584369449378331,
  'Food/Water': 0.0905861456483126},
 '18': {'Savings Group': 0.6984126984126984,
  'Food/Water': 0.23809523809523808,
  'Farming/Labour': 0.06349206349206349},
 '19': {'Savings Group': 1.0},
 '20': {'Savings Group': 1.0},
 '21': {'Farming/Labour': 0.47619047619047616,
  'Food/Water': 0.3333333333333333,
  'Shop': 0.09523809523809523,
  'Fuel/Energy': 0.047619047619047616,
  'Transport': 0.047619047619047616},
 '22': {'Food/Water': 0.33040588654165676,
  'Farming/Labour': 0.3209114645145977,
  'Shop': 0.164016140517446,
  'None': 0.06147638262520769,
  'Fuel/Energy': 0.05008307619273677,
  'Transport': 0.028957987182530263,
  'Savings Group': 0.023973415618324233,
  'Education': 0.014478993591265131,
  'Health': 0.0035604082601471635,
  'Environment': 0.0011868027533823878,
  'Staff': 0.00047472110135295516,
  'Chama': 0.00023736055067647758,
  'Game': 0.00023736055067647758},
 '23': {'Savings Group': 0.8323424494649228,
  'Farming/Labour': 0.16765755053507728},
 '24': {'Farming/Labour': 0.38481675392670156,
  'Food/Water': 0.3717277486910995,
  'Shop': 0.1387434554973822,
  'Fuel/Energy': 0.05235602094240838,
  'Transport': 0.02356020942408377,
  'Savings Group': 0.01832460732984293,
  'Education': 0.007853403141361256,
  'Staff': 0.002617801047120419},
 '25': {'Savings Group': 0.7916666666666666,
  'Food/Water': 0.20833333333333334},
 '26': {'Savings Group': 0.7442348008385744, 'Food/Water': 0.2557651991614256},
 '27': {'Food/Water': 0.3333333333333333,
  'Farming/Labour': 0.25,
  'Health': 0.25,
  'Savings Group': 0.08333333333333333,
  'Fuel/Energy': 0.08333333333333333},
 '28': {'Food/Water': 1.0},
 '29': {'Food/Water': 0.27335640138408307,
  'Farming/Labour': 0.23529411764705882,
  'Shop': 0.21972318339100347,
  'Fuel/Energy': 0.21280276816608998,
  'None': 0.03806228373702422,
  'Education': 0.006920415224913495,
  'Transport': 0.006920415224913495,
  'Savings Group': 0.005190311418685121,
  'Staff': 0.0017301038062283738},
 '30': {'Food/Water': 0.36228287841191065,
  'Shop': 0.2679900744416873,
  'Farming/Labour': 0.21712158808933002,
  'Savings Group': 0.08436724565756824,
  'Education': 0.02481389578163772,
  'Fuel/Energy': 0.018610421836228287,
  'Transport': 0.017369727047146403,
  'None': 0.0037220843672456576,
  'Health': 0.0024813895781637717,
  'Environment': 0.0012406947890818859},
 '31': {'Savings Group': 0.8,
  'Food/Water': 0.13333333333333333,
  'Shop': 0.06666666666666667},
 '32': {'Savings Group': 0.7444444444444445,
  'Farming/Labour': 0.2,
  'Food/Water': 0.05555555555555555},
 '33': {'Food/Water': 0.33343474292668085,
  'Farming/Labour': 0.28414968055978096,
  'Savings Group': 0.18892607240644965,
  'Shop': 0.1146942500760572,
  'Fuel/Energy': 0.06936416184971098,
  'None': 0.006693033160937024,
  'Education': 0.0027380590203833284},
 '34': {'Savings Group': 1.0},
 '35': {'Food/Water': 0.3829787234042553,
  'Farming/Labour': 0.2390488110137672,
  'Shop': 0.1902377972465582,
  'Savings Group': 0.07259073842302878,
  'Transport': 0.060075093867334166,
  'Health': 0.030037546933667083,
  'Fuel/Energy': 0.016270337922403004,
  'None': 0.0050062578222778474,
  'Education': 0.0037546933667083854},
 '36': {'Savings Group': 1.0},
 '37': {'Farming/Labour': 0.5454545454545454,
  'Food/Water': 0.36363636363636365,
  'Savings Group': 0.045454545454545456,
  'Shop': 0.045454545454545456},
 '38': {'Savings Group': 1.0},
 '39': {'Savings Group': 1.0},
 '40': {'Farming/Labour': 0.3595236417447678,
  'Food/Water': 0.3165386512578395,
  'Shop': 0.18842928616728913,
  'Fuel/Energy': 0.05108871820167712,
  'None': 0.0360439715312522,
  'Transport': 0.022443802409978154,
  'Education': 0.01039391163413431,
  'Savings Group': 0.00842083010358678,
  'Health': 0.004545134240011275,
  'Staff': 0.0011627087590726517,
  'Environment': 0.0010570079627933197,
  'System': 0.00035233598759777326},
 '41': {'Food/Water': 0.33003300330033003,
  'Farming/Labour': 0.2739273927392739,
  'Shop': 0.1782178217821782,
  'Savings Group': 0.13861386138613863,
  'Health': 0.0429042904290429,
  'Fuel/Energy': 0.0165016501650165,
  'Transport': 0.0165016501650165,
  'Education': 0.0033003300330033004},
 '42': {'Savings Group': 0.8661740558292282, 'Health': 0.13382594417077176},
 '43': {'Savings Group': 1.0},
 '44': {'Food/Water': 0.4805194805194805,
  'Shop': 0.14285714285714285,
  'Savings Group': 0.14285714285714285,
  'Farming/Labour': 0.13636363636363635,
  'Health': 0.06493506493506493,
  'Transport': 0.012987012987012988,
  'Environment': 0.012987012987012988,
  'Fuel/Energy': 0.006493506493506494},
 '45': {'Food/Water': 0.35471100554235946,
  'Farming/Labour': 0.2414885193982581,
  'Shop': 0.23198733174980204,
  'Education': 0.03800475059382423,
  'None': 0.035629453681710214,
  'Transport': 0.035629453681710214,
  'Fuel/Energy': 0.028503562945368172,
  'Savings Group': 0.02454473475851148,
  'Health': 0.006334125098970704,
  'Environment': 0.001583531274742676,
  'Staff': 0.000791765637371338,
  'System': 0.000791765637371338},
 '46': {'Savings Group': 0.6981132075471698,
  'Health': 0.18867924528301888,
  'Food/Water': 0.09433962264150944,
  'Shop': 0.018867924528301886},
 '47': {'Savings Group': 0.5555555555555556,
  'Farming/Labour': 0.2222222222222222,
  'Food/Water': 0.2222222222222222},
 '48': {'Food/Water': 0.38795180722891565,
  'Savings Group': 0.38313253012048193,
  'Health': 0.10120481927710843,
  'Shop': 0.09879518072289156,
  'Fuel/Energy': 0.016867469879518072,
  'Farming/Labour': 0.012048192771084338},
 '49': {'Food/Water': 0.3829787234042553,
  'Savings Group': 0.3829787234042553,
  'Education': 0.19148936170212766,
  'Fuel/Energy': 0.0425531914893617},
 'external': {'Food/Water': 0.6,
  'Fuel/Energy': 0.1,
  'Health': 0.03,
  'Education': 0.015,
  'Savings Group': 0.065,
  'Shop': 0.19}}

# agent:[centrality,allocationValue]
agentAllocation = {'0': [1, 1],
 '1': [1, 1],
 '2': [1, 1],
 '3': [1, 1],
 '4': [1, 1],
 '5': [1, 1],
 '6': [1, 1],
 '7': [1, 1],
 '8': [1, 1],
 '9': [1, 1],
 '10': [1, 1],
 '11': [1, 1],
 '12': [1, 1],
 '13': [1, 1],
 '14': [1, 1],
 '15': [1, 1],
 '16': [1, 1],
 '17': [1, 1],
 '18': [1, 1],
 '19': [1, 1],
 '20': [1, 1],
 '21': [1, 1],
 '22': [1, 1],
 '23': [1, 1],
 '24': [1, 1],
 '25': [1, 1],
 '26': [1, 1],
 '27': [1, 1],
 '28': [1, 1],
 '29': [1, 1],
 '30': [1, 1],
 '31': [1, 1],
 '32': [1, 1],
 '33': [1, 1],
 '34': [1, 1],
 '35': [1, 1],
 '36': [1, 1],
 '37': [1, 1],
 '38': [1, 1],
 '39': [1, 1],
 '40': [1, 1],
 '41': [1, 1],
 '42': [1, 1],
 '43': [1, 1],
 '44': [1, 1],
 '45': [1, 1],
 '46': [1, 1],
 '47': [1, 1],
 '48': [1, 1],
 '49': [1, 1]}